name: release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Publish
        run: |
          exit 0

  release:
    runs-on: ubuntu-latest
    needs: [publish]

    steps:
      - name: Release
        run: |
          exit 1

  clean-up:
    runs-on: ubuntu-latest
    needs: [release]
    if: failure()
    steps:
      - name: Cleanup
        run: |
          exit 0
  
  deploy:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Deploy
        run: |
          exit 0