name: release

on:
  push:
    branches:
      - main

jobs:
  semver:
    runs-on: ubuntu-latest
    outputs:
      semver: "0.0.1"
    steps:
      - name: Publish
        run: |
          exit 0

  publish:
    runs-on: ubuntu-latest
    needs: [semver]
    if: always() && needs.semver.outputs.semver != ''
    steps:
      - name: Publish
        run: |
          exit 0

  release:
    runs-on: ubuntu-latest
    needs: [publish]

    steps:
      - name: Release
        run: |
          exit 0

  clean-up:
    runs-on: ubuntu-latest
    needs: [release]
    if: failure()
    steps:
      - name: Cleanup
        run: |
          exit 0
  
  deploy:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Deploy
        run: |
          exit 0